# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='active_status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done'), ('delayed', 'delayed')], default='pending', max_length=20),
        ),
    ]
