# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20171226_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='github',
            field=models.URLField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hp_no',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True, max_length=50),
        ),
    ]
